In [33]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

In [3]:
df=pd.read_csv('emails.csv')

In [4]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [5]:
df.shape

(5172, 3002)

In [6]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [7]:
df.drop(columns='Email No.', inplace=True)

In [8]:
df.columns

Index(['the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou', 'in',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3001)

In [9]:
df.describe()

the           to          ect          and          for  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000   
mean      6.640565     6.188128     5.143852     3.075599     3.124710   
std      11.745009     9.534576    14.101142     6.045970     4.680522   
min       0.000000     0.000000     1.000000     0.000000     0.000000   
25%       0.000000     1.000000     1.000000     0.000000     1.000000   
50%       3.000000     3.000000     1.000000     1.000000     2.000000   
75%       8.000000     7.000000     4.000000     3.000000     4.000000   
max     210.000000   132.000000   344.000000    89.000000    47.000000   

                of            a          you          hou           in  ...  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  ...   
mean      2.627030    55.517401     2.466551     2.024362    10.600155  ...   
std       6.229845    87.574172     4.314444     6.967878    19.281892  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000    12.000000     0.000000     0.000000     1.000000  ...   
50%       1.000000    28.000000     1.000000     0.000000     5.000000  ...   
75%       2.000000    62.250000     3.000000     1.000000    12.000000  ...   
max      77.000000  1898.000000    70.000000   167.000000   223.000000  ...   

          connevey          jay       valued          lay  infrastructure  \
count  5172.000000  5172.000000  5172.000000  5172.000000     5172.000000   
mean      0.005027     0.012568     0.010634     0.098028        0.004254   
std       0.105788     0.199682     0.116693     0.569532        0.096252   
min       0.000000     0.000000     0.000000     0.000000        0.000000   
25%       0.000000     0.000000     0.000000     0.000000        0.000000   
50%       0.000000     0.000000     0.000000     0.000000        0.000000   
75%       0.000000     0.000000     0.000000     0.000000        0.000000   
max       4.000000     7.000000     2.000000    12.000000        3.000000   

          military     allowing           ff          dry   Prediction  
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  
mean      0.006574     0.004060     0.914733     0.006961     0.290023  
std       0.138908     0.072145     2.780203     0.098086     0.453817  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     1.000000     0.000000     1.000000  
max       4.000000     3.000000   114.000000     4.000000     1.000000  

[8 rows x 3001 columns]

In [11]:
df.Prediction.unique()

array([0, 1], dtype=int64)

In [12]:
df['Prediction']=df['Prediction'].replace({0:'Not Spam', 1:'Spam'})

In [13]:
df.head()

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  valued  \
0    0   0    1    0    0   0    2    0    0   0  ...         0    0       0   
1    8  13   24    6    6   2  102    1   27  18  ...         0    0       0   
2    0   0    1    0    0   0    8    0    0   4  ...         0    0       0   
3    0   5   22    0    5   1   51    2   10   1  ...         0    0       0   
4    7   6   17    1    5   2   57    0    9   3  ...         0    0       0   

   lay  infrastructure  military  allowing  ff  dry  Prediction  
0    0               0         0         0   0    0    Not Spam  
1    0               0         0         0   1    0    Not Spam  
2    0               0         0         0   0    0    Not Spam  
3    0               0         0         0   0    0    Not Spam  
4    0               0         0         0   1    0    Not Spam  

[5 rows x 3001 columns]

KNN

In [15]:
X= df.drop(columns='Prediction',axis=1)
Y=df['Prediction']

In [16]:
x_train,x_test,y_train,y_test= train_test_split(X,Y,test_size=0.2,random_state=1)

In [17]:
KN=KNeighborsClassifier
knn=KN(n_neighbors=7)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [24]:
x_test = np.ascontiguousarray(x_test)


In [25]:
y_pred_knn= knn.predict(x_test)

C:\Users\Aarushi\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [26]:
print(y_pred_knn)

['Not Spam' 'Spam' 'Not Spam' ... 'Not Spam' 'Not Spam' 'Not Spam']


In [27]:
M=metrics.accuracy_score(y_test,y_pred_knn)
print('KNN accuarcy: ',M)


KNN accuarcy:  0.8714975845410629


In [29]:
C= metrics.confusion_matrix(y_test,y_pred_knn)
print('Confusion Matrix: \n', C)

Confusion Matrix: 
 [[635  84]
 [ 49 267]]


In [34]:
print('KNN Classifcation Report: \n')
print(classification_report(y_test,y_pred_knn))

KNN Classifcation Report: 

              precision    recall  f1-score   support

    Not Spam       0.93      0.88      0.91       719
        Spam       0.76      0.84      0.80       316

    accuracy                           0.87      1035
   macro avg       0.84      0.86      0.85      1035
weighted avg       0.88      0.87      0.87      1035



SVM

In [48]:
model=SVC(kernel='linear',probability=True)
model.fit(x_train,y_train)
y_pred_svm= model.predict(x_test)

C:\Users\Aarushi\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [49]:
M = metrics.accuracy_score(y_test,y_pred_svm)
print("SVM accuracy: ", M)

SVM accuracy:  0.9507246376811594


In [50]:
print("SVM Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

SVM Confusion Matrix:
 [[693  26]
 [ 25 291]]


In [51]:
print("SVM Classification Report:")
print(classification_report(y_test, y_pred_svm))

SVM Classification Report:
              precision    recall  f1-score   support

    Not Spam       0.97      0.96      0.96       719
        Spam       0.92      0.92      0.92       316

    accuracy                           0.95      1035
   macro avg       0.94      0.94      0.94      1035
weighted avg       0.95      0.95      0.95      1035

